version: "3"
services:
  auth:
    image: teambinarymatter/ctse-auth:latest
    container_name: auth
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    env_file:
      - stack.env
    networks:
      payzy-network:
        ipv4_address: 172.20.0.121
    restart: unless-stopped

  product:
    image: teambinarymatter/ctse-ms-2:latest
    container_name: product
    labels:
      com.centurylinklabs.watchtower.enable: true
    ports:
      - "5002:5002"
    env_file:
      - stack.env
    networks:
      payzy-network:
        ipv4_address: 172.20.0.122
    restart: unless-stopped

  gateway:
    image: teambinarymatter/ctse-gateway:latest
    container_name: gateway
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - user
      - product
    ports:
      - "5000:5000"
    networks:
      payzy-network:
        ipv4_address: 172.20.0.120
    restart: unless-stopped

networks:
  payzy-network:
    name: payzy-network
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
